pipelines:
  swagger-compose:
    group: swagger
    label_template: "${git[:8]}"
    materials:
      git:
        git: git@github.com:ai-traders/swagger-composer.git
        branch: master
    stages:
      - build:
          clean_workspace: true
          jobs:
            build:
              resources:
               - docker
               - small
              artifacts:
               - build:
                   source: "build/libs/swagger-composer-*.jar"
                   destination: build
              tasks:
               - exec:
                   command: ide
                   arguments:
                    - "gradle build test fatJar"
      - release:
          clean_workspace: true
          approval:
            type: manual
          jobs:
            github:
              resources:
               - docker
               - small
              tasks:
               - exec:
                   command: bash
                   arguments:
                    - ./release.sh
